"""
Constants and character mappings for Arabic Typing Helper
"""

# Basic harakat characters with keyboard shortcuts
BASIC_HARAKAT_CHARS = [
    ('ٍ', 'Tanwin Kasrah', '7'),
    ('ٌ', 'Tanwin Dammah', '8'),
    ('ـ', 'Kashida', '9'),
    ('ْ', 'Sukun', '4'),
    ('ّ', 'Shaddah', '5'),
    ('ً', 'Tanwin Fathah', '6'),
    ('َ', 'Fathah', '1'),
    ('ِ', 'Kasrah', '2'),
    ('ُ', 'Dammah', '3'),
    ('\u0619', 'Dammah Kecil', '0'),
]

# Comprehensive advanced harakat characters
ADVANCED_HARAKAT_CHARS = [
    ('\u064B', 'Fathah Ganda'),
    ('\u064D', 'Kasrah Ganda'),
    ('\u064C', 'Dammah Ganda'),
    ('\u0652', 'Sukun'),
    ('\u0651', 'Shaddah'),
    ('\u0670', 'Alef Atas'),
    ('\u0656', 'Alef Bawah'),
    ('\u065F', 'Hamza Bergelombang Bawah'),
    ('\u0640', 'Tatweel'),
    ('\u064E', 'Fathah'),
    ('\u0650', 'Kasrah'),
    ('\u064F', 'Dammah'),
    ('\u0653', 'Maddah'),
    ('\u0654', 'Hamza Atas'),
    ('\u0655', 'Hamza Bawah'),
    ('\u0657', 'Dammah Terbalik'),
    ('\u0658', 'Tanda Nun Ghunnah'),
    ('\u0659', 'Zwarakay'),
    ('\u065A', 'Tanda Vokal V Kecil'),
    ('\u065B', 'Tanda Vokal V Kecil Terbalik'),
    ('\u065C', 'Tanda Vokal Titik Bawah'),
    ('\u065D', 'Dammah Terbalik'),
    ('\u065E', 'Fathah Dua Titik'),
    ('\u065F', 'Waslah'),
    ('\u0660', 'Angka Arab-Hindi Nol'),
    ('\u0661', 'Angka Arab-Hindi Satu'),
    ('\u0662', 'Angka Arab-Hindi Dua'),
    ('\u0663', 'Angka Arab-Hindi Tiga'),
    ('\u0664', 'Angka Arab-Hindi Empat'),
    ('\u0665', 'Angka Arab-Hindi Lima'),
    ('\u0666', 'Angka Arab-Hindi Enam'),
    ('\u0667', 'Angka Arab-Hindi Tujuh'),
    ('\u0668', 'Angka Arab-Hindi Delapan'),
    ('\u0669', 'Angka Arab-Hindi Sembilan'),
    ('\u066A', 'Persen Arab'),
    ('\u066B', 'Desimal Arab'),
    ('\u066C', 'Ribuan Arab'),
    ('\u066D', 'Asterisk Arab'),
    ('\u0671', 'Alef Wasla'),
    ('\u0672', 'Alef dengan Wavy Hamza'),
    ('\u0673', 'Alef dengan Hamza Terbalik'),
    ('\u0674', 'Hamza Tinggi'),
    ('\u0675', 'Hamza Alef Tinggi'),
    ('\u0676', 'Waw Hamza Tinggi'),
    ('\u0677', 'Waw Dammah'),
    ('\u0678', 'Yeh Hamza Tinggi'),
    ('\u0679', 'Tteh'),
    ('\u067A', 'Tteheh'),
    ('\u067B', 'Beeh'),
    ('\u067C', 'Teh dengan Ring'),
    ('\u067D', 'Teh dengan Tiga Titik'),
    ('\u067E', 'Peh'),
    ('\u067F', 'Teheh'),
    ('\u0680', 'Beheh'),
    ('\u0681', 'Hah dengan Hamza'),
    ('\u0682', 'Hah dengan Dua Titik'),
    ('\u0683', 'Nyeh'),
    ('\u0684', 'Dyeh'),
    ('\u0685', 'Hah dengan Tiga Titik'),
    ('\u0686', 'Tcheh'),
    ('\u0687', 'Tcheheh'),
    ('\u0688', 'Ddal'),
    ('\u0689', 'Dal dengan Ring'),
    ('\u068A', 'Dal dengan Titik'),
    ('\u068B', 'Dal dengan Tiga Titik'),
    ('\u068C', 'Dahal'),
    ('\u068D', 'Ddahal'),
    ('\u068E', 'Dul'),
    ('\u068F', 'Dal dengan Tiga Titik Bawah'),
    ('\u0690', 'Dal dengan Empat Titik'),
    ('\u0691', 'Rreh'),
    ('\u0692', 'Reh dengan V Kecil'),
    ('\u0693', 'Reh dengan Ring'),
    ('\u0694', 'Reh dengan Titik'),
    ('\u0695', 'Reh dengan V Kecil Bawah'),
    ('\u0696', 'Reh dengan Titik Bawah'),
    ('\u0697', 'Reh dengan Dua Titik'),
    ('\u0698', 'Jeh'),
    ('\u0699', 'Reh dengan Empat Titik'),
    ('\u069A', 'Seen dengan Titik Bawah'),
    ('\u069B', 'Seen dengan Tiga Titik'),
    ('\u069C', 'Seen dengan Tiga Titik Bawah'),
    ('\u069D', 'Sad dengan Dua Titik'),
    ('\u069E', 'Sad dengan Tiga Titik'),
    ('\u069F', 'Tah dengan Tiga Titik'),
    ('\u06A0', 'Ain dengan Tiga Titik'),
    ('\u06A1', 'Dotless Feh'),
    ('\u06A2', 'Feh dengan Titik'),
    ('\u06A3', 'Feh dengan Titik Bawah'),
    ('\u06A4', 'Veh'),
    ('\u06A5', 'Feh dengan Tiga Titik'),
    ('\u06A6', 'Peheh'),
    ('\u06A7', 'Qaf dengan Titik'),
    ('\u06A8', 'Qaf dengan Tiga Titik'),
    ('\u06A9', 'Keheh'),
    ('\u06AA', 'Swash Kaf'),
    ('\u06AB', 'Kaf dengan Ring'),
    ('\u06AC', 'Kaf dengan Titik'),
    ('\u06AD', 'Ng'),
    ('\u06AE', 'Kaf dengan Tiga Titik'),
    ('\u06AF', 'Gaf'),
    ('\u06B0', 'Gaf dengan Ring'),
    ('\u06B1', 'Ngoeh'),
    ('\u06B2', 'Gaf dengan Dua Titik'),
    ('\u06B3', 'Gueh'),
    ('\u06B4', 'Gaf dengan Tiga Titik'),
    ('\u06B5', 'Lam dengan V Kecil'),
    ('\u06B6', 'Lam dengan Titik'),
    ('\u06B7', 'Lam dengan Tiga Titik'),
    ('\u06B8', 'Lam dengan Tiga Titik Bawah'),
    ('\u06B9', 'Noon dengan Titik'),
    ('\u06BA', 'Noon Ghunna'),
    ('\u06BB', 'Rnoon'),
    ('\u06BC', 'Noon dengan Ring'),
    ('\u06BD', 'Noon dengan Tiga Titik'),
    ('\u06BE', 'Heh Doachashmee'),
    ('\u06BF', 'Tcheh dengan Titik'),
    ('\u06C0', 'Heh dengan Yeh'),
    ('\u06C1', 'Heh Goal'),
    ('\u06C2', 'Heh Goal dengan Hamza'),
    ('\u06C3', 'Teh Marbuta Goal'),
    ('\u06C4', 'Waw dengan Ring'),
    ('\u06C5', 'Kirghiz Oe'),
    ('\u06C6', 'Oe'),
    ('\u06C7', 'U'),
    ('\u06C8', 'Yu'),
    ('\u06C9', 'Kirghiz Yu'),
    ('\u06CA', 'Waw dengan Dua Titik'),
    ('\u06CB', 'Veh'),
    ('\u06CC', 'Farsi Yeh'),
    ('\u06CD', 'Yeh dengan Ekor'),
    ('\u06CE', 'Yeh dengan V Kecil'),
    ('\u06CF', 'Waw dengan Titik'),
    ('\u06D0', 'Yeh dengan Dua Titik Bawah'),
    ('\u06D1', 'Yeh dengan Tiga Titik'),
    ('\u06D2', 'Yeh Barree'),
    ('\u06D3', 'Yeh Barree dengan Hamza'),
]

# Arabic symbols
SYMBOL_CHARS = [
    ('؟', 'Tanda Tanya'),
    ('؛', 'Titik Koma'),
    ('،', 'Koma'),
    ('؎', 'Pemisah Tanggal'),
    ('؏', 'Penanda Catatan Kaki'),
    ('ؐ', 'Tanda Sallallaahu Alayhe Wasallam'),
    ('ؑ', 'Tanda Alayhe Assallam'),
    ('ؒ', 'Tanda Rahmatullahi Alayhe'),
    ('ؓ', 'Tanda Radi Allaahu Anhu'),
    ('ؔ', 'Tanda Radi Allaahu Anha'),
    ('؈', 'Sinar'),
    ('؉', 'Rub El Hizb'),
    ('؊', 'Takhallus'),
    ('؋', 'Tanda Afghani'),
    ('؍', 'Misra'),
    ('\u06DD', 'Akhir Ayat'),
    ('\u06DE', 'Awal Rub El Hizb'),
    ('\u06DF', 'Tiga Titik Atas'),
    ('\u06E0', 'Tanda Baca V Kecil'),
    ('\u06E1', 'Tanda Baca V Kecil Atas'),
    ('\u06E2', 'Tanda Baca Mim'),
    ('\u06E3', 'Tanda Baca V Kecil Bawah'),
    ('\u06E4', 'Tanda Baca Madda'),
    ('\u06E5', 'Tanda Baca Waw'),
    ('\u06E6', 'Tanda Baca Yeh'),
    ('\u06E7', 'Tanda Baca Yeh dengan Hamza'),
    ('\u06E8', 'Tanda Baca Yeh dengan Hamza Atas'),
    ('\u06E9', 'Tanda Lokasi Sajda'),
    ('\u06EA', 'Tanda Kosong Atas'),
    ('\u06EB', 'Tanda Kosong Bawah'),
    ('\u06EC', 'Tanda Bulat'),
    ('\u06ED', 'Tanda Maqam'),
]

# Keyboard mappings
KEYBOARD_MAPPINGS = {
    "ABC": {
        'q': 'q', 'w': 'w', 'e': 'e', 'r': 'r', 't': 't',
        'y': 'y', 'u': 'u', 'i': 'i', 'o': 'o', 'p': 'p',
        'a': 'a', 's': 's', 'd': 'd', 'f': 'f', 'g': 'g',
        'h': 'h', 'j': 'j', 'k': 'k', 'l': 'l',
        'z': 'z', 'x': 'x', 'c': 'c', 'v': 'v', 'b': 'b',
        'n': 'n', 'm': 'm'
    },
    "Arabic": {
        'q': 'ض', 'w': 'ص', 'e': 'ث', 'r': 'ق', 't': 'ف',
        'y': 'غ', 'u': 'ع', 'i': 'ه', 'o': 'خ', 'p': 'ح',
        'a': 'ش', 's': 'س', 'd': 'ي', 'f': 'ب', 'g': 'ل',
        'h': 'ا', 'j': 'ت', 'k': 'ن', 'l': 'م',
        'z': 'ئ', 'x': 'ء', 'c': 'ؤ', 'v': 'ر', 'b': 'ﻻ',
        'n': 'ى', 'm': 'ة'
    }
}

# Pegon mapping
PEGON_MAPPING = {
    'q': ('ق', 'ك'), 'w': ('و', 'ؤ'), 'e': ('ء', 'ئ'), 'r': ('ر', 'ذ'), 't': ('ت', 'ث'),
    'y': ('ي', 'ى'), 'u': ('ى', 'ء'), 'i': ('ا', 'إ'), 'o': ('ه', 'ة'), 'p': ('ط', 'ظ'),
    'a': ('ا', 'أ'), 's': ('ش', 'س'), 'd': ('د', 'ض'), 'f': ('ق', 'غ'), 'g': ('غ', 'ع'),
    'h': ('ح', 'خ'), 'j': ('ج', 'چ'), 'k': ('ك', 'خ'), 'l': ('ل', 'آ'),
    'z': ('ز', 'ژ'), 'x': ('خ', 'ث'), 'c': ('ص', 'ض'), 'v': ('ف', 'ڤ'), 'b': ('ب', 'پ'),
    'n': ('ن', 'ں'), 'm': ('م', 'م')
}

# Harakat keyboard shortcuts
HARAKAT_MAPPING = {
    '1': 'َ', '2': 'ِ', '3': 'ُ', '4': 'ْ', '5': 'ّ',
    '6': 'ً', '7': 'ٍ', '8': 'ٌ', '9': 'ـ', '0': '\u0619'
}

# Keyboard layout rows
KEYBOARD_ROWS = [
    ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '⌫'],
    ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Enter'],
    ['Z', 'X', 'C', 'V', 'B', 'N', 'M', 'Del', 'Salin']
]

# Font settings
DEFAULT_FONTS = [
    "Noto Sans Arabic", "Arial Unicode MS", "Times New Roman", 
    "Tahoma", "Amiri", "Scheherazade"
]

# UI Settings
UI_SETTINGS = {
    'window_size': (1200, 600),
    'min_size': (800, 400),
    'button_min_height': 60,
    'button_min_width': 80,
    'harakat_font_size': 28,
    'keyboard_font_size': 16,
    'text_area_font_size': 20,
    'instruction_font_size': 14,
    'button_font_size': 14,
    'highlight_color': '#007ACC',
    'highlight_duration': 150
}
